language: php

services:
  - mysql

php:
  - 5.6

addons:
  hosts:
    - mysql

before_script:
  - mysql -u root -e "SET GLOBAL sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'"
  - mysql -u root -e "USE mysql; UPDATE user SET authentication_string=PASSWORD('password') WHERE user='root'; FLUSH PRIVILEGES;"
  - mysql -u root -ppassword < .docker/config/mysql/light_orm_mysql.sql
  - travis_retry composer self-update
  - travis_retry composer update $PREFER_LOWEST
  - composer install

script:
  - vendor/bin/phpcs --standard=phpcs.xml -p ./src -p ./tests
  - vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.xml
  - vendor/bin/behat

after_success:
  bash <(curl -s https://codecov.io/bash)
