language: php

services:
  - mysql

php:
  - 7.1

addons:
  hosts:
    - mysql

before_script:
  - travis_retry composer self-update
  - travis_retry composer update $PREFER_LOWEST
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -u root -ppassword < .docker/config/mysql/light_orm_mysql.sql
  - composer install

script:
  - vendor/bin/phpcs --standard=phpcs.xml -p ./src -p ./tests
  - vendor/bin/phpstan analyse -l 2 ./src
  - vendor/bin/phpunit --coverage-clover=coverage.xml --coverage-xml=var/phpunit/coverage-xml --log-junit=var/phpunit/phpunit.junit.xml
  - vendor/bin/infection --threads=4 --only-covered --coverage=var/phpunit
  - vendor/bin/behat

after_success:
  bash <(curl -s https://codecov.io/bash)
