language: php

services:
  - mysql

php:
  - 5.6

addons:
  hosts:
    - mysql

before_script:
  - make travis-before-script

script:
  - make travis-script

after_success:
  - make travis-after-success
