---
language: php

services:
  - mysql

php:
  - "7.1"

addons:
  hosts:
    - mysql

before_script:
  - mysql -u root -e "SET GLOBAL sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'"
  - mysql -u root -e "USE mysql; UPDATE user SET authentication_string=PASSWORD('password') WHERE user='root'; FLUSH PRIVILEGES;"
  - mysql -u root -ppassword < .docker/config/mysql/light_orm_mysql.sql
  - travis_retry composer self-update
  - travis_retry composer update $PREFER_LOWEST
  - composer install

script:
  - vendor/bin/phpcs --standard=phpcs.xml -p ./src -p ./tests
  - vendor/bin/phpstan analyse -l 2 ./src
  - vendor/bin/phpunit --coverage-clover=coverage-phpunit.xml --coverage-xml=var/phpunit/coverage-xml --log-junit=var/phpunit/phpunit.junit.xml
  - vendor/bin/infection --threads=4 --only-covered --coverage=var/phpunit
  - vendor/bin/behat
  - vendor/bin/phpcov merge --clover=coverage-behat.xml var/behat/coverage-cov

after_success:
  - bash <(curl -s https://codecov.io/bash) -cF phpunit -f coverage-phpunit.xml
  - bash <(curl -s https://codecov.io/bash) -cF behat -f coverage-behat.xml
